# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
pandoc_version: 1.19.2.1
latex: false

branches:
  only:
    - master

r_packages:
  - bookdown
  - tinytex
  - ggplot2

before_install:
  - sudo apt-get update
  - sudo timedatectl set-timezone Asia/Taipei  # Set timezone to Taiwan
  - sudo apt-get install fonts-arphic-bkai00mp # install AR PL KaitiM Big5



script:
  - R -e 'tinytex::install_tinytex()'
  - Rscript -e 'rmarkdown::render("main.Rmd", output_format = "bookdown::html_document2")'
  - Rscript -e 'rmarkdown::render("main.Rmd", output_format = "bookdown::pdf_document2")'
  - mkdir docs
  - cp main.html docs/index.html
  - cp -r main.pdf docs/index.pdf


# deploy docs/ and master branch to branch 'gh-pages'
deploy:
  - provider: pages    # Deploy master/docs to branch gh-pages
    skip-cleanup: true
    github-token: $GH_TOKEN  
    keep-history: false
    local-dir: docs    # Web output directory
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
