# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
cache: packages
pandoc_version: 1.19.2.1


before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo timedatectl set-timezone Asia/Taipei  # Set timezone to Taiwan


script:
  - Rscript -e 'rmarkdown::render("main.Rmd", output_format = "bookdown::html_document2")'
  - mkdir docs
  - cp main.html docs/index.html


# deploy docs/ and master branch to branch 'gh-pages'
deploy:
  - provider: pages    # Deploy master/docs to branch gh-pages
    skip-cleanup: true
    github-token: $GH_TOKEN  
    keep-history: false
    local-dir: docs    # Web output directory
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
