---
title: "R Markdown as an Authoring Tool in Linguistics"
author: '`r ifelse(knitr::is_html_output(), "Yongfu Liao", "Yongfu Liao (廖永賦)\\thanks{National Taiwan University, Taipei, Taiwan}")`'
date: "`r format(Sys.Date(), '%B %d, %Y')`"
bibliography: author-ling.bib
csl: style_sheets/apa.csl
link-citations: yes
always_allow_html: yes
output:
  bookdown::html_document2:
    includes:
    number_sections: TRUE
    css: style_sheets/style.css
    df_print: kable
    toc: true
    toc_depth: 2
    toc_float:
        collapsed: false
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: TRUE
    toc: False
    includes:
      in_header: style_sheets/header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.pos = 'H',
	fig.align = 'center'
)
library(knitr)
library(dplyr)

cond_cmpl <- function(html = NULL, latex = NULL) {
  if (knitr::is_html_output()) return(html)
  else return(latex)
}
```

# Abstract {-}

**bold**

\blfootnote{There is an online version of this article with animated figures. To have a better reading experience, visit \textbf{\href{http://bit.ly/LingRmd}{bit.ly/LingRmd}}. The source of this artilce can be found at \url{https://github.com/liao961120/ling-rmd}.}

\pagenumbering{gobble}

\newpage 
\pagenumbering{arabic}

```{r child = '1-intro.Rmd'}
```

```{r child = '2-method.Rmd'}
```

```{r child = '3-result.Rmd'}
```

```{r child = '4-discussion.Rmd'}
```


# References {-}
